const tintColorLight = "#2f95dc";
const tintColorDark = "#fff";

export default {
  light: {
    text: "#000",
    background: "#fff",
    tint: tintColorLight,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#fff",
    background: "#000",
    tint: tintColorDark,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorDark,
  },
};

export const COLORS = {
  Light: {
    background: "#fff",
    colorOne: "#DC3868",
    colorOneLight: "rgba(220, 56, 104, 0.08)",
    colorOneLightA: "rgba(220, 56, 104, 0.20)",
    colorTwo: "#0898A0",
    colorThree: "#E0457B",
    colorFour: "#000",
    colorFive: "rgba(255, 255, 255, 0.40)",
    colorFiveIn: "rgba(255, 255, 255, 0.10)",
    greyText: "rgba(35, 35, 35, 0.4)",
    deepGreyColor: "#838384",
    deeperGreyColor: "#646464",
    hashBackGround: "#F5F3F3",
    hashBackGroundL2: "#F3F3F3",
    hashBackGroundL3: "#F2F2F2",
    hashHomeBackGround: "#EDEDED",
    hashHomeBackGroundL2: "#F9F9F9",
    hashHomeBackGroundL3: "#D3D3D3",
    gray: "#4F4F4F",
    tickGray: "#BDBDBD",
    modalOverlay: "rgba(31, 32, 33, 0.4)",
    colorBlueBackGround: " rgba(38, 120, 242, 0.08)",
    colorSeven: "rgba(113, 135, 156, 0.10)",
    colorSeven10: "rgba(113, 135, 156, 0.10)",
    colorEight: "#FEFAF7",
    colorNine: "#FE7122",
    colorNineB: "#FD9326",
    colorTen: "#FDF4F9",
    colorEleven: "#B80074",
    colorTwelve: "#F6FFFE",
    colorThirteen: "#0BA190",
    colorThirteenB: "rgba(11, 161, 144, 0.08)",
    colorFourteen: "#E94753",
    colorFourteenB: "#C70B1A",
    colorFifteen: "#0BA290",
    colorSixTeen: "rgba(64, 187, 195, 0.15)",
    colorSeventeen: "#41BCC4",
    colorEighteen: "rgba(0, 0, 0, 0.40)",
    colorNineteen: "#F7F7F7",
    colorTwenty: "rgba(235, 87, 87, 0.17)",
    colorTwentyOne: "#F8F8F8",
    colorTwentyFour: "#71879C",
    colorTwentyFive: "#222",
    colorTwentySix: "#E1E8ED",
    colorTwentySixReal: "#D0D2D1",
    colorTwentySeven: "#292F33",
    colorL1: "rgba(255, 255, 255, 0.06) 99.99%",
    colorL2: "#FFF",
    colorOverlay: "rgba(31, 32, 33, 0.40)",
    colorBlue: "#0B66C3",
  },
  Dark: {},
};

export const SIZES = {
  sizeOne: 8,
  sizeTwo: 9,
  sizeThree: 10,
  sizeFour: 11,
  sizeFive: 12,
  sizeFiveB: 13,
  sizeFiveC: 14,
  sizeSix: 15,
  sizeSixB: 16,
  sizeSixC: 17,
  sizeSeven: 18,
  sizeSevenB: 19,
  sizeEight: 20,
  sizeEightA: 22,
  sizeEightB: 23,
  sizeNine: 25,
  sizeNineB: 28,
  sizeTen: 30,
  sizeEleven: 40,
};

export const IMAGES = {
  devotionalSample1: require("../shared/assets/images/png/devotional-sample-picture-1.png"),
  devotionalSample2: require("../shared/assets/images/png/devotional-sample-picture-2.png"),
  devotionalSample3: require("../shared/assets/images/png/devotional-sample-picture-3.png"),
  devotionalSample4: require("../shared/assets/images/png/devotional-sample-picture-4.png"),
  splashScreen1: require("../shared/assets/images/png/splash-screen-image1.png"),
  splashScreen2: require("../shared/assets/images/png/splash-screen-image-2.png"),
  splashScreen3: require("../shared/assets/images/png/splash-screen-image-3.png"),
  bamSplashScreen: require("../shared/assets/images/png/bam-splash-screen.png"),
  logoDailyAnswer: require("../shared/assets/images/png/Logo-Daily-Answer.png"),
  googleLogo: require("../shared/assets/images/png/google.png"),
  facebookLogo: require("../shared/assets/images/png/facebook.png"),
};

export const IconBottomBar = {};
